### ISSUE TITLE
No (visible) progress at downloading stage

### ISSUE THREAD

**Issue by WouterPennings** [Typiqally/epsilon#34] opened 2022-06-28 23:15 UTC
![image](https://user-images.githubusercontent.com/58933609/176319485-ae619d9e-b722-4f8d-90a0-c45704f1567c.png)
It is stuck at this stage for the whole time, without showing any from of progress.

**Comment by NealGeilen** [comment] 2022-06-29 07:30
We fixed this in the new release ![New log](https://user-images.githubusercontent.com/12190745/176268592-e863e4c3-47b4-4af5-aeca-298d53a37c33.gif). The user receives now more information on the progress of the data collection. 
Therefore this issue will now be closed

**Comment by Typiqally** [comment] 2022-06-29 07:31
Duplicate of #28

**Closed as completed by NealGeilen** 2022-06-29 07:30 UTC
Labels: duplicate
